print ("halloo semuaa perkenalkan aku Farras!")
print (" ╱|、 ")
print ("(˚ˎ 。7 ")
print (" |、˜〵 ")
print (" じしˍ,)ノ ")
print ("***********************************************************")
print ("Nama lengkap : Vania Farras Kalista")
print ("NIM : 2611533026")
print ("Program Studi : Informatika")
print ("Tempat, tanggal lahir : Jakarta 4 september 2008")
print ("Harapan : Semoga aku bisa mendapatkan ilmu yang bermanfaat")
print ("***********************************************************")