<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA & PEMOGRAMAN**

**“TIPE DATA DAN VARIABEL PYTHON”**

**Disusun Oleh :**

**Vania Farras Kalista**

**2611533026**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="Images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

<h2 align="center">KATA PENGANTAR</h2>

Puji syukur penulis panjatkan kehadirat Tuhan Yang Maha Esa, karena atas rahmat dan karunia-Nya penulis dapat menyelesaikan laporan praktikum yang berjudul "Tipe Data dan Variabel Python" ini dengan baik.

Laporan ini disusun sebagai salah satu syarat untuk memenuhi tugas praktikum mata kuliah Pratikum Algoritma dan Pemrograman, sekaligus sebagai sarana untuk memperdalam pemahaman mengenai konsep dasar tipe data dan variabel dalam bahasa pemrograman Python, meliputi string, boolean, tipe data numerik (integer, float, dan complex), fungsi input(), serta konstanta.

Dalam proses penyusunan laporan ini, penulis menyadari masih terdapat banyak kekurangan, baik dari segi penulisan maupun pembahasan materi. Oleh karena itu, penulis sangat mengharapkan kritik dan saran yang membangun demi kesempurnaan laporan ini di masa yang akan datang.

Penulis juga mengucapkan terima kasih kepada dosen pengampu mata kuliah yang telah memberikan bimbingan, arahan, serta ilmu yang bermanfaat selama proses perkuliahan dan praktikum berlangsung. Tidak lupa pula penulis mengucapkan terima kasih kepada asisten praktikum yang telah membimbing, mendampingi, serta memberikan arahan selama pelaksanaan praktikum berlangsung, sehingga laporan ini dapat terselesaikan dengan baik.

Akhir kata, penulis berharap laporan ini dapat memberikan manfaat serta menambah wawasan bagi pembaca, khususnya dalam memahami konsep dasar tipe data dan variabel pada bahasa pemrograman Python.

<div align="right" style="margin-left:-30px;">
Padang, 2026
<br>
<br>
Vania Farras Kalista
<br>
2611533026
</div>

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Python merupakan salah satu bahasa pemrograman yang banyak digunakan saat ini karena sintaksnya yang sederhana dan mudah dipahami, baik oleh pemula maupun programmer berpengalaman. Dalam mempelajari suatu bahasa pemrograman, pemahaman mengenai tipe data dan variabel menjadi fondasi paling dasar yang wajib dikuasai, karena hampir seluruh proses dalam program mulai dari menyimpan data, melakukan perhitungan, hingga pengambilan keputusan selalu melibatkan penggunaan variabel dan tipe data tertentu.

Variabel berfungsi sebagai tempat penyimpanan data yang nilainya dapat berubah selama program berjalan, sedangkan tipe data menentukan jenis nilai apa yang dapat disimpan dan operasi apa saja yang dapat dilakukan terhadap nilai tersebut, seperti string, boolean, integer, float, dan complex. Tanpa pemahaman yang baik mengenai konsep ini, seorang pemrogram akan kesulitan dalam menulis program yang benar, efisien, dan bebas dari kesalahan (error), terutama kesalahan yang berkaitan dengan ketidaksesuaian tipe data.

Oleh karena itu, praktikum mengenai tipe data dan variabel Python ini dilakukan sebagai langkah awal untuk membangun pemahaman dasar sebelum mempelajari konsep pemrograman yang lebih kompleks, seperti struktur kontrol, fungsi, dan struktur data lanjutan.

## 1.2 Tujuan
1. Memahami konsep dasar variabel dalam bahasa pemrograman Python, termasuk cara mendeklarasikan dan memberi nilai pada variabel.
2. Mengenal berbagai jenis tipe data dasar dalam Python, yaitu string, boolean, dan numerik (integer, float, complex).
3. Memahami cara penggunaan fungsi input() untuk menerima data masukan dari pengguna.
4. Memahami konsep konstanta serta perbedaannya dengan variabel biasa dalam Python.
5. Mampu menerapkan tipe data dan variabel tersebut dalam program Python sederhana.

## 1.3 Manfaat
1. Praktikum ini memberikan pemahaman dasar yang kuat mengenai tipe data dan variabel, sehingga memudahkan dalam mempelajari materi pemrograman Python selanjutnya yang lebih kompleks.
2. Meningkatkan kemampuan logika pemrograman, karena pemilihan tipe data yang tepat akan berpengaruh pada efisiensi dan keakuratan program yang dibuat.
3. Mengurangi kesalahan dalam penulisan program, sebab dengan memahami karakteristik masing-masing tipe data, praktikan dapat menghindari kesalahan umum seperti type error saat mengolah data.
4. Sebagai bekal praktis, pemahaman tipe data dan variabel ini dapat langsung diterapkan dalam pembuatan program nyata, seperti aplikasi input data pengguna, kalkulasi sederhana, hingga sistem yang lebih besar.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori
### 2.1.1 Python
Python adalah bahasa pemrograman tingkat tinggi yang bersifat general-purpose, artinya dapat digunakan untuk berbagai keperluan pengembangan, mulai dari aplikasi web, analisis data, kecerdasan buatan, hingga otomasi tugas. Python dikembangkan dengan filosofi readability, sehingga strukturnya menyerupai bahasa manusia dan mudah dipahami oleh pemula.

### 2.1.2 string
String adalah tipe data yang digunakan untuk menyimpan dan mengelola teks. String merupakan kumpulan karakter yang disusun secara berurutan dan diperlakukan sebagai satu kesatuan data, di mana karakternya bisa berupa huruf, angka, simbol, maupun spasi. Contoh data string antara lain nama pengguna, kalimat, alamat email, dan kata sandi. 

Beberapa karakteristik penting string:
1. Terdiri dari kumpulan karakter dan memiliki panjang (length) tertentu 
2. Setiap karakter dapat diakses menggunakan indeks, mirip seperti array 
3. Secara konsep, string sering direpresentasikan sebagai array karakter, misalnya string "DATA" memiliki indeks D(0), A(1), T(2), A(3) 

Dalam Python, string dituliskan menggunakan tanda kutip tunggal ('...') atau ganda ("..."), contoh: nama = "Budi". Operasi dasar yang umum dilakukan pada string meliputi mengakses karakter berdasarkan indeks, penggabungan (concatenation), menghitung panjang string, membandingkan dua string, pencarian karakter/kata, serta pemotongan bagian string (substring/slicing).


### 2.1.3 Boolean
Boolean adalah tipe data logika yang hanya memiliki dua kemungkinan nilai: benar atau salah. Dalam Python, nilai boolean ditulis sebagai True dan False (huruf awal kapital), dan tipe datanya disebut bool.

Boolean umumnya dihasilkan dari operasi perbandingan (misalnya 5 > 3 menghasilkan True) atau digunakan sebagai kondisi dalam percabangan (if) dan perulangan. Secara konsep umum pada bahasa pemrograman, setiap nilai juga dapat dievaluasi secara implisit sebagai benar atau salah. nilai seperti angka nol, string kosong, atau None/null umumnya dianggap salah sedangkan nilai-nilai lainnya dianggap benar. Boolean sangat penting dalam pengambilan keputusan di dalam program.

### 2.1.4 Numerik
Python menyediakan tiga tipe data numerik utama:
1. Integer (int) — bilangan bulat, baik positif maupun negatif, tanpa angka desimal. Contoh: 10, -5, 1000.
2. Float (float) — bilangan pecahan/desimal (floating point). Contoh: 3.14, -0.5, 2.0.
3. Complex (complex) — bilangan kompleks yang terdiri dari bagian real dan imajiner, ditulis dengan akhiran j. Contoh: 3+5j, 2-4j.

Ketiga tipe ini dapat dicek menggunakan fungsi bawaan type(), misalnya type(10) akan menghasilkan <class 'int'>. Python juga mendukung konversi antar tipe numerik (casting), seperti int(), float(), dan complex(), serta operasi aritmetika standar (+, -, *, /, //, %, **) yang berlaku pada tipe-tipe ini.

### 2.1.5 Fungsi Input
Fungsi input() digunakan untuk mengizinkan pengguna memasukkan data (input) ke dalam program.
Sintaksnya adalah: input(prompt) di mana parameter prompt berupa string yang merepresentasikan pesan yang ditampilkan sebelum pengguna memasukkan data. Parameter ini bersifat opsional.

Perlu dicatat bahwa nilai yang dikembalikan oleh input() selalu bertipe string, sehingga jika ingin diolah sebagai angka, hasilnya perlu dikonversi terlebih dahulu menggunakan int() atau float().

### 2.1.6 Konstanta
Konstanta (atau nilai konstan) adalah sebuah variabel yang nilainya dideklarasikan di awal dan tidak bisa diubah setelahnya.Python sendiri sebenarnya tidak memiliki mekanisme konstanta bawaan secara native seperti bahasa lain (misalnya const di JavaScript). Namun, deklarasi konstanta di Python dapat dilakukan dengan bantuan tipe dari modul typing, yaitu Final, yang perlu diimpor terlebih dahulu.

Final hanya memberikan informasi ke type checker (seperti mypy/Pylance) bahwa suatu variabel bersifat konstan — pada saat program dijalankan (runtime), Python tidak akan menghasilkan error meskipun nilai variabel yang ditandai Final tersebut diubah, karena sifat immutable ini hanya berlaku di level pengecekan tipe, bukan di runtime. 

Sebagai konvensi, berdasarkan panduan gaya penulisan kode PEP 8, nama konstanta di Python dituliskan dalam huruf besar semua (UPPER_CASE), misalnya PI, MAX_VALUE, TOTAL_MONTH

## 2.2 Kode Program

### 2.2.1 Program "Numerik_2611533026"
Program Python dibuat menggunakan Visual Studio Code. Pada praktikum ini, Python digunakan untuk membuat dan menjalankan program sederhana bertema tipe data numerik, guna mengenal cara Python mendeklarasikan variabel serta mengidentifikasi tipe data integer, float, dan complex menggunakan fungsi `type()`.

In [1]:
#Buat file dengan nama Numerik_2611533026.py
#Buat variabel tipe interger
a_3026 = 100
print("the type of variable having value", a_3026, "is", type(a_3026))

#Buat variabel tipe float
b_3026 = 10.2345
print("the type of variable having value", b_3026, "is", type(b_3026))

#buat variabel tipe kompleks
c_3026 = 100 + 3j
print("the type of variable having value", c_3026, "is", type(c_3026))

#note : gunanya program ini untuk mengetahui tipe data dari variabel yang telah dibuat

the type of variable having value 100 is <class 'int'>
the type of variable having value 10.2345 is <class 'float'>
the type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**

1. `#` digunakan sebagai simbol untuk membuat komentar satu baris dalam bahasa Python, dan tidak akan dieksekusi oleh interpreter.
2. `a_3026 = 100` digunakan untuk membuat variabel bernama `a_3026` dan mengisinya dengan nilai `100`, yang merupakan tipe data **integer** (bilangan bulat).
3. `b_3026 = 10.2345` digunakan untuk membuat variabel bernama `b_3026` dan mengisinya dengan nilai `10.2345`, yang merupakan tipe data **float** (bilangan desimal/pecahan).
4. `c_3026 = 100 + 3j` digunakan untuk membuat variabel bernama `c_3026` dan mengisinya dengan nilai `100 + 3j`, yang merupakan tipe data **complex** (bilangan kompleks dengan bagian real dan imajiner).
5. `type()` digunakan untuk memeriksa dan menampilkan tipe data dari suatu variabel.
6. `print()` digunakan untuk menampilkan data atau teks ke layar.
7. Tanda koma (`,`) di dalam `print()` digunakan untuk memisahkan beberapa nilai (teks dan variabel) yang ingin ditampilkan sekaligus dalam satu baris output.

### 2.2.2 Program "String_2611533026"
Program Python dibuat menggunakan Visual Studio Code. Pada praktikum ini, Python digunakan untuk membuat dan menjalankan program sederhana bertema data pribadi, guna mengenal cara Python mendeklarasikan variabel bertipe string serta menampilkannya ke layar menggunakan fungsi `print()`.

In [1]:
#program data pribadi
nama_3026 = "Vania Farras kalista"
jenis_kelamin_3026 = 'Perempuan'
alamat_3026 = "Griya insani Jl Durian tarung kota Padang"
agama_3026 = "Islam"

print("Nama saya adalah", nama_3026)
print("Jenis kelamin saya adalah", jenis_kelamin_3026)
print("Alamat saya adalah", alamat_3026)
print("Agama saya adalah", agama_3026)

Nama saya adalah Vania Farras kalista
Jenis kelamin saya adalah Perempuan
Alamat saya adalah Griya insani Jl Durian tarung kota Padang
Agama saya adalah Islam


**Penjelasan :**
1. `#program data pribadi` digunakan sebagai komentar satu baris dalam bahasa Python untuk memberi keterangan mengenai isi program, dan tidak akan dieksekusi oleh interpreter.
2. `nama_3026 = "Vania Farras kalista"` digunakan untuk membuat variabel bernama nama_3026 dan mengisinya dengan teks nama, yang merupakan tipe data string.
3. `jenis_kelamin_3026 = 'Perempuan'` digunakan untuk membuat variabel bernama jenis_kelamin_3026 dan mengisinya dengan teks jenis kelamin, yang juga bertipe string (ditulis menggunakan tanda kutip tunggal).
4. `alamat_3026 = "Griya insani Jl Durian tarung kota Padang"` digunakan untuk membuat variabel bernama alamat_3026 dan mengisinya dengan teks alamat, yang bertipe string.
5. `agama_3026 = "Islam"` digunakan untuk membuat variabel bernama agama_3026 dan mengisinya dengan teks agama, yang bertipe string.
6. `print()` digunakan untuk menampilkan data atau teks ke layar.
7. `Tanda koma (,)` di dalam `print()` digunakan untuk memisahkan teks statis (kalimat) dengan nilai variabel yang ingin ditampilkan sekaligus dalam satu baris output.

### 2.2.3 Program "Boolean_2611533026"
Program Python dibuat menggunakan Visual Studio Code. Pada praktikum ini, Python digunakan untuk membuat dan menjalankan program sederhana bertema pengecekan kelulusan, guna mengenal penggunaan tipe data boolean, operator perbandingan, serta struktur kondisi if dalam bahasa Python.

In [2]:
#Deklarasi variabel dengan tipe data boolean
is_lulus_3026 = True
is_cumlaude_3026 = True

#Menggunakan Boolean
nilai_3026 = 85
Batas_lulus_3026 = 75

#Menentukan nilai Boolean dari kondisi
status_kelulusan_3026 = nilai_3026 >= Batas_lulus_3026 #hasilnya True karena 85 lebih besar dari 75

print("=== Check Kelulusan ===")
print("Nilai:", nilai_3026)
print("Apakah lulus?", status_kelulusan_3026)

if is_lulus_3026 and is_cumlaude_3026:
    print("Selamat, Anda lulus dengan predikat Cumlaude!!")

=== Check Kelulusan ===
Nilai: 85
Apakah lulus? True
Selamat, Anda lulus dengan predikat Cumlaude!!


**Penjelasan :**
1. `#Deklarasi variabel dengan tipe data boolean` digunakan sebagai komentar satu baris dalam bahasa Python untuk memberi keterangan mengenai isi program, dan tidak akan dieksekusi oleh interpreter.
2. `is_lulus_3026 = True` digunakan untuk membuat variabel bernama `is_lulus_3026` dan mengisinya dengan nilai `True`, yang merupakan tipe data **boolean**.
3. `is_cumlaude_3026 = True` digunakan untuk membuat variabel bernama `is_cumlaude_3026` dan mengisinya dengan nilai `True`, yang juga bertipe **boolean**.
4. `nilai_3026 = 85` digunakan untuk membuat variabel bernama `nilai_3026` dan mengisinya dengan nilai `85`, yang bertipe **integer**, sebagai nilai ujian.
5. `Batas_lulus_3026 = 75` digunakan untuk membuat variabel bernama `Batas_lulus_3026` dan mengisinya dengan nilai `75`, yang bertipe **integer**, sebagai batas minimum kelulusan.
6. `status_kelulusan_3026 = nilai_3026 >= Batas_lulus_3026` digunakan untuk membandingkan nilai `nilai_3026` dengan `Batas_lulus_3026` menggunakan operator perbandingan `>=` (lebih besar sama dengan). Hasil perbandingan ini otomatis berupa nilai **boolean** (`True` atau `False`) yang disimpan ke variabel `status_kelulusan_3026`. Pada kasus ini hasilnya `True` karena `85` lebih besar dari `75`.
7. `print("=== Check Kelulusan ===")` digunakan untuk menampilkan teks judul sebagai pemisah/header pada output.
8. `print("Nilai:", nilai_3026)` digunakan untuk menampilkan teks beserta nilai dari variabel `nilai_3026` ke layar.
9. `print("Apakah lulus?", status_kelulusan_3026)` digunakan untuk menampilkan teks beserta nilai boolean dari variabel `status_kelulusan_3026` ke layar.
10. `if is_lulus_3026 and is_cumlaude_3026:` merupakan struktur kondisi yang akan menjalankan blok kode di bawahnya hanya jika kedua variabel boolean (`is_lulus_3026` **dan** `is_cumlaude_3026`) bernilai `True`. Operator `and` digunakan untuk menggabungkan dua kondisi logika, di mana kondisi keseluruhan hanya bernilai `True` jika kedua kondisi tersebut sama-sama `True`.
11. `print("Selamat, Anda lulus dengan predikat Cumlaude!!")` digunakan untuk menampilkan pesan selamat ke layar, yang hanya akan dieksekusi apabila kondisi pada `if` di atas terpenuhi (bernilai `True`).

### 2.2.4 Program "Input_2611533026"
Pada praktikum ini, Python digunakan untuk membuat dan menjalankan program sederhana bertema perhitungan luas persegi panjang, guna mengenal penggunaan fungsi input() untuk menerima data dari pengguna serta proses konversi tipe data dari string ke integer.

In [ ]:
#Program menghitung luas persegi panjang
#program ini menggunakan fungsi input untuk meminta pengguna memasukan nilai
#nilai yang dimasukkan akan dikonversi menjadi tipe data integer agar bisa dilakukan operasi perkalian
panjang_3026 = input('Masukkan nilai panjang: ')
lebar_3026 = input('Masukkan nilai lebar: ')
luas_3026 = int(panjang_3026) * int(lebar_3026)
print("luas =", luas_3026)

**Penjelasan :**
1. `#Program menghitung luas persegi panjang` digunakan sebagai komentar satu baris dalam bahasa Python untuk memberi keterangan mengenai isi program, dan tidak akan dieksekusi oleh interpreter.
2. `#program ini menggunakan fungsi input untuk meminta pengguna memasukan nilai` merupakan komentar tambahan yang menjelaskan bahwa program menggunakan fungsi `input()` untuk mengambil data dari pengguna.
3. `#nilai yang dimasukkan akan dikonversi menjadi tipe data integer agar bisa dilakukan operasi perkalian` merupakan komentar yang menjelaskan bahwa nilai input akan diubah tipe datanya menjadi integer sebelum dikalikan.
4. `panjang_3026 = input('Masukkan nilai panjang: ')` digunakan untuk menampilkan pesan `"Masukkan nilai panjang: "` ke layar dan menunggu pengguna memasukkan data. Nilai yang dimasukkan pengguna akan disimpan ke variabel `panjang_3026`, namun perlu diketahui bahwa hasil dari fungsi `input()` selalu bertipe **string**, meskipun pengguna mengetikkan angka.
5. `lebar_3026 = input('Masukkan nilai lebar: ')` digunakan untuk menampilkan pesan `"Masukkan nilai lebar: "` ke layar dan menyimpan nilai yang dimasukkan pengguna ke variabel `lebar_3026`, yang juga masih bertipe **string**.
6. `luas_3026 = int(panjang_3026) * int(lebar_3026)` digunakan untuk menghitung luas persegi panjang. Fungsi `int()` digunakan untuk mengonversi (*casting*) nilai `panjang_3026` dan `lebar_3026` dari tipe **string** menjadi tipe **integer**, karena operasi perkalian (`*`) tidak dapat dilakukan langsung pada data bertipe string. Hasil perkalian tersebut kemudian disimpan ke variabel `luas_3026`.
7. `print("luas =", luas_3026)` digunakan untuk menampilkan teks `"luas ="` beserta nilai hasil perhitungan luas yang tersimpan pada variabel `luas_3026` ke layar.

### 2.2.5 Program "Konstanta_2611533026"
Program Python dibuat menggunakan Visual Studio Code. Pada praktikum ini, Python digunakan untuk membuat dan menjalankan program sederhana bertema perhitungan luas lingkaran, guna mengenal penggunaan konstanta (Final), fungsi input() yang dikonversi ke tipe float, serta format string menggunakan operator %.

In [5]:
#Program ini menggunakan konstanta untuk menghitung luas lingkaran

from typing import Final
PI: Final[float] = 3.14  # konstanta phi
print("pi: %f" % (PI))
jari_3026 = float(input('Masukkan nilai jari-jari:'))
luas_3026 = PI * jari_3026* jari_3026
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3026, luas_3026))

pi: 3.140000
Luas lingkaran dengan jari-jari 23.00 adalah 1661.06


**Penjelasan :**
1. `#Program ini menggunakan konstanta untuk menghitung luas lingkaran` digunakan sebagai komentar satu baris dalam bahasa Python untuk memberi keterangan mengenai isi program, dan tidak akan dieksekusi oleh interpreter.
2. `from typing import Final` digunakan untuk meng-*import* tipe `Final` dari modul `typing`, yang merupakan bagian dari Python standard library. Tipe `Final` ini digunakan untuk menandai suatu variabel sebagai **konstanta**.
3. `PI: Final[float] = 3.14  # konstanta phi` digunakan untuk membuat konstanta bernama `PI` dengan tipe data `float` dan nilai `3.14`. Penandaan `Final[float]` memberi tahu type checker bahwa nilai `PI` bertipe float dan tidak boleh diubah selama program berjalan. Di bagian akhir baris terdapat komentar `# konstanta phi` yang menjelaskan bahwa variabel ini merepresentasikan nilai konstanta matematika π (phi).
4. `print("pi: %f" % (PI))` digunakan untuk menampilkan nilai konstanta `PI` ke layar. Tanda `%f` merupakan format specifier yang digunakan untuk menampilkan nilai bertipe float, sedangkan operator `%` di luar tanda kutip digunakan untuk menyisipkan nilai `PI` ke posisi `%f` tersebut.
5. `jari_3026 = float(input('Masukkan nilai jari-jari:'))` digunakan untuk menampilkan pesan `"Masukkan nilai jari-jari:"` dan meminta pengguna memasukkan data. Karena hasil dari `input()` selalu bertipe string, fungsi `float()` digunakan untuk mengonversi (*casting*) nilai tersebut menjadi tipe **float**, agar dapat digunakan dalam operasi perhitungan matematika. Hasilnya disimpan ke variabel `jari_3026`.
6. `luas_3026 = PI * jari_3026* jari_3026` digunakan untuk menghitung luas lingkaran menggunakan rumus luas lingkaran (π × r × r), yaitu mengalikan konstanta `PI` dengan variabel `jari_3026` sebanyak dua kali. Hasil perhitungan disimpan ke variabel `luas_3026`.
7. `print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3026, luas_3026))` digunakan untuk menampilkan hasil perhitungan ke layar. Format specifier `%.2f` digunakan untuk menampilkan nilai float dengan pembulatan sebanyak 2 angka di belakang koma, dan operator `%` di luar tanda kutip digunakan untuk menyisipkan nilai `jari_3026` dan `luas_3026` secara berurutan ke dalam teks tersebut.

---
## Tugas Praktikum

**Soal :**

<div align="center">
<img src="Images/soal_tugas.png" width="500"><br>
<em>Gambar 2.2 : Soal Tugas Praktikum</em>
</div>

**Kode Jawaban :**

a. Kode Program "tugas2_2611533026"

In [4]:
from typing import Final
# Konstanta batas kelulusan
BATAS_LULUS: Final[float] = 75.0

print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")

# Input data praktikan
nama_3026 = input("Masukkan Nama Mahasiswa : ")
jenis_kelamin_3026 = input("Masukkan Jenis Kelamin (L/P): ")
umur_3026 = int(input("Masukkan Umur : "))
nilai_3026 = float(input("Masukkan Skor Tes Awal : "))

# Alamat domisili multiline
alamat_3026 = "Griya insani, Jl Durian tarung, Padang"

# Token identifikasi berupa bilangan kompleks
token_3026 = 100 + 3j

# Evaluasi status kelulusan
lulus_3026 = nilai_3026 >= BATAS_LULUS

print("\n=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")

print("Nama Mahasiswa :", nama_3026, "| Tipe:", type(nama_3026))

print("Alamat Domisili:")
print(alamat_3026, "| Tipe:", type(alamat_3026))

print("Umur :", umur_3026, "tahun | Tipe:", type(umur_3026))
print("Skor Tes Awal :", nilai_3026, "| Tipe:", type(nilai_3026))
print("ID Token Sinyal:", token_3026, "| Tipe:", type(token_3026))

print("\n=== STATUS KELULUSAN PRAKTIKUM ===")
print("Batas Minimum Nilai:", BATAS_LULUS)
print("Apakah Dinyatakan Lulus?:", lulus_3026, "| Tipe:", type(lulus_3026))

=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===

=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===
Nama Mahasiswa : Vania Farras Kalista | Tipe: <class 'str'>
Alamat Domisili:
Griya insani, Jl Durian tarung, Padang | Tipe: <class 'str'>
Umur : 18 tahun | Tipe: <class 'int'>
Skor Tes Awal : 99.9 | Tipe: <class 'float'>
ID Token Sinyal: (100+3j) | Tipe: <class 'complex'>

=== STATUS KELULUSAN PRAKTIKUM ===
Batas Minimum Nilai: 75.0
Apakah Dinyatakan Lulus?: True | Tipe: <class 'bool'>



**Penjelasan :**
1. `from typing import Final` digunakan untuk meng-*import* tipe `Final` dari modul `typing`, yang digunakan untuk mendeklarasikan **konstanta** dalam Python.
2. `# Konstanta batas kelulusan` merupakan komentar satu baris yang menjelaskan tujuan dari variabel di baris berikutnya, dan tidak dieksekusi oleh interpreter.
3. `BATAS_LULUS: Final[float] = 75.0` digunakan untuk membuat konstanta bernama `BATAS_LULUS` bertipe `float` dengan nilai `75.0`, yang akan dijadikan acuan batas minimum kelulusan. Penulisan nama dengan huruf besar semua (`UPPER_CASE`) merupakan konvensi penamaan konstanta pada Python.
4. `print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")` digunakan untuk menampilkan teks judul/header program ke layar.
5. `# Input data praktikan` merupakan komentar yang menjelaskan bahwa baris-baris di bawahnya berkaitan dengan proses input data.
6. `nama_3026 = input("Masukkan Nama Mahasiswa : ")` digunakan untuk meminta pengguna memasukkan nama, dan hasilnya disimpan ke variabel `nama_3026` dengan tipe data **string**.
7. `jenis_kelamin_3026 = input("Masukkan Jenis Kelamin (L/P): ")` digunakan untuk meminta pengguna memasukkan jenis kelamin, dan hasilnya disimpan sebagai tipe **string**.
8. `umur_3026 = int(input("Masukkan Umur : "))` digunakan untuk meminta pengguna memasukkan umur. Karena hasil `input()` selalu bertipe string, fungsi `int()` digunakan untuk langsung mengonversi (*casting*) nilai tersebut menjadi tipe **integer** sebelum disimpan ke variabel `umur_3026`.
9. `nilai_3026 = float(input("Masukkan Skor Tes Awal : "))` digunakan untuk meminta pengguna memasukkan skor tes awal, kemudian mengonversinya menjadi tipe **float** menggunakan fungsi `float()`.
10. `# Alamat domisili multiline` merupakan komentar yang menjelaskan tujuan dari variabel di baris berikutnya.
11. `alamat_3026 = "Griya insani, Jl Durian tarung, Padang"` digunakan untuk membuat variabel bertipe **string** yang berisi teks alamat domisili.
12. `# Token identifikasi berupa bilangan kompleks` merupakan komentar yang menjelaskan tujuan dari variabel di baris berikutnya.
13. `token_3026 = 100 + 3j` digunakan untuk membuat variabel bernama `token_3026` dengan tipe data **complex**, terdiri dari bagian real (`100`) dan bagian imajiner (`3j`).
14. `# Evaluasi status kelulusan` merupakan komentar yang menjelaskan tujuan dari variabel di baris berikutnya.
15. `lulus_3026 = nilai_3026 >= BATAS_LULUS` digunakan untuk membandingkan `nilai_3026` dengan konstanta `BATAS_LULUS` menggunakan operator `>=`. Hasil perbandingan ini berupa nilai **boolean** (`True` atau `False`) yang disimpan ke variabel `lulus_3026`.
16. `print("\n=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")` digunakan untuk menampilkan teks header ke layar. Karakter `\n` di awal teks digunakan untuk membuat baris kosong baru sebelum teks ditampilkan, agar output lebih rapi.
17. `print("Nama Mahasiswa :", nama_3026, "| Tipe:", type(nama_3026))` digunakan untuk menampilkan nama beserta tipe datanya. Fungsi `type()` digunakan untuk memeriksa dan menampilkan tipe data dari suatu variabel.
18. `print("Alamat Domisili:")` dan `print(alamat_3026, "| Tipe:", type(alamat_3026))` digunakan untuk menampilkan label "Alamat Domisili" pada satu baris, kemudian isi alamat beserta tipe datanya pada baris berikutnya.
19. `print("Umur :", umur_3026, "tahun | Tipe:", type(umur_3026))` digunakan untuk menampilkan umur beserta satuan "tahun" dan tipe datanya.
20. `print("Skor Tes Awal :", nilai_3026, "| Tipe:", type(nilai_3026))` digunakan untuk menampilkan skor tes awal beserta tipe datanya.
21. `print("ID Token Sinyal:", token_3026, "| Tipe:", type(token_3026))` digunakan untuk menampilkan nilai token (bilangan kompleks) beserta tipe datanya.
22. `print("\n=== STATUS KELULUSAN PRAKTIKUM ===")` digunakan untuk menampilkan header baru pada baris kosong berikutnya.
23. `print("Batas Minimum Nilai:", BATAS_LULUS)` digunakan untuk menampilkan nilai konstanta `BATAS_LULUS` ke layar.
24. `print("Apakah Dinyatakan Lulus?:", lulus_3026, "| Tipe:", type(lulus_3026))` digunakan untuk menampilkan status kelulusan (`True`/`False`) beserta tipe datanya, yaitu **boolean**.

---
# BAB III
# KESIMPULAN

Berdasarkan seluruh praktikum yang telah dilakukan, dapat disimpulkan beberapa hal sebagai berikut:

1. Python bersifat ***dynamically typed***, artinya tipe data suatu variabel tidak perlu dideklarasikan secara eksplisit, melainkan otomatis ditentukan berdasarkan nilai yang diberikan saat variabel dibuat. Hal ini dapat diverifikasi menggunakan fungsi bawaan `type()`.

2. Python menyediakan beberapa tipe data dasar yang masing-masing memiliki fungsi dan karakteristik berbeda:
   - String digunakan untuk menyimpan data berupa teks, seperti nama, alamat, dan jenis kelamin.
   - Boolean (`True`/`False`) digunakan untuk merepresentasikan nilai logika, umumnya dihasilkan dari operasi perbandingan dan digunakan dalam pengambilan keputusan melalui struktur kondisi `if`.
   - Numerik (integer, float, dan complex) digunakan untuk menyimpan dan mengolah data berupa angka, baik bilangan bulat, desimal, maupun bilangan kompleks.

3. Fungsi `input()` memungkinkan program menerima data secara interaktif dari pengguna. Namun, nilai yang dihasilkan `input()` selalu bertipe **string**, sehingga apabila data tersebut akan digunakan dalam operasi matematika, diperlukan proses konversi tipe data (*casting*) menggunakan fungsi seperti `int()` atau `float()`.

4. **Konstanta** dalam Python dapat dideklarasikan dengan bantuan `Final` dari modul `typing`. Meskipun Python tidak melarang perubahan nilai konstanta pada saat runtime, penandaan `Final` tetap berguna sebagai informasi bagi type checker dan sebagai konvensi penulisan kode yang baik (nama konstanta ditulis dengan huruf besar/`UPPER_CASE`), sesuai standar PEP 8.

5. Pada program terakhir, seluruh tipe data dan konsep tersebut (string, boolean, integer, float, complex, konstanta, dan `input()`) berhasil digabungkan dalam satu program sistem registrasi praktikan yang lebih kompleks, yang menunjukkan bahwa pemahaman terhadap tipe data dan variabel merupakan fondasi penting sebelum membangun program yang lebih besar dan terstruktur.

Secara keseluruhan, praktikum ini memberikan pemahaman dasar yang kuat mengenai variabel dan tipe data di Python, sehingga dapat menjadi bekal untuk mempelajari materi pemrograman Python yang lebih lanjut, seperti struktur kontrol, fungsi, dan struktur data.

---
## DAFTAR PUSTAKA

[1] Universitas Telkom Jakarta, "String dan Implementasinya dalam Struktur Data," Artikel Universitas Telkom Jakarta, 2026. [Online]. Tersedia: https://jakarta.telkomuniversity.ac.id/string-dan-implementasinya-dalam-struktur-data/ [Diakses 13 September 2026].

[2] web.dev, "Boolean," Learn JavaScript, web.dev. [Online]. Tersedia: https://web.dev/learn/javascript/data-types/boolean?hl=id [Diakses 13 September 2026].

[3] W3Schools, "Python input() Function," W3Schools Python Reference. [Online]. Tersedia: https://www.w3schools.com/python/ref_func_input.asp [Diakses 13 September 2026].

[4] N. A. Prayogo, "A.5. Python Konstanta," Dasar Pemrograman Python, 2026. [Online]. Tersedia: https://dasarpemrogramanpython.novalagung.com/basic/konstanta [Diakses 13 September 2026].

[5] Python Software Foundation, "typing — Support for type hints," Python 3 Documentation. [Online]. Tersedia: https://docs.python.org/3/library/typing.html#typing.Final [Diakses 13 September 2026].